phrase:
  project_id: 23f9f82fbb097f7291b6f952d9d7de52
  push:
    sources:
    - file: ./source-locale/main/android-strings/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: strings.xml, Brand-Specific-Strings
  pull:
    targets:
    - file: ./translation-files/de/strings.xml
      params:
        locale_id: de
        file_format: xml
        tags: strings.xml, Brand-Specific-Strings
    - file: ./translation-files/es/strings.xml
      params:
        locale_id: es
        file_format: xml
        tags: strings.xml, Brand-Specific-Strings
    - file: ./translation-files/el/strings.xml
      params:
        locale_id: el
        file_format: xml
        tags: strings.xml, Brand-Specific-Strings
    - file: ./source-locale/main/android-strings/strings.xml
      params:
        locale_id: en
        file_format: xml
        tags: strings.xml, Brand-Specific-Strings
