phrase:
  project_id: daec31f3d59d8f0bf5c9fd80b48e6c4b
  push:
    sources:
    - file: ./source-locale/main/android-strings/strings.xml
      params:
        file_format: android
        locale_id: en
        update_translations: true
  pull:
    targets:
    - file: ./translation-files/de/strings.xml
      params:
        locale_id: de
        file_format: android
    - file: ./translation-files/es/strings.xml
      params:
        locale_id: es
        file_format: android
    - file: ./translation-files/el/strings.xml
      params:
        locale_id: el
        file_format: android
    - file: ./source-locale/main/android-strings/strings.xml
      params:
        locale_id: en
        file_format: android
